{% set name = "py-pandoc-crossref" %}
{% set version = "0.3.6.2.1" %}
{% set dep_ver = "0.3.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec0690c864a8923c6ad88eccdb197c365e8c008c94a2e48207053a027e2c1d35
  patches:
    - conda.patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandoc-crossref ={{ dep_ver }}
    - py-pandoc >=2.9.2,<2.10

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/kiwi0fruit/py-pandoc-crossref
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "Installs pandoc-crossref conda package in pip and conda."
  doc_url: https://github.com/kiwi0fruit/py-pandoc-crossref
  dev_url: https://github.com/kiwi0fruit/py-pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
