{% set name = "py-pandoc-crossref" %}
{% set version = "0.3.4.0.5" %}
{% set dep_ver = "0.3.4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f142fa558c51f63b3e978793df6d751699768de978b89d2ca621c2e92ab5b36c
  patches:
    - conda.patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandoc-crossref ={{ dep_ver }}
    - py-pandoc >=2.7,<2.8

test:
  commands:
    - pandoc-crossref --version
    - pandoc-crossref --help

about:
  home: https://github.com/kiwi0fruit/py-pandoc-crossref
  license: "GPLv2+"
  license_family: GPL
  license_file: LICENSE
  summary: "Installs pandoc-crossref conda package in pip and conda."
  doc_url: https://github.com/kiwi0fruit/py-pandoc-crossref
  dev_url: https://github.com/kiwi0fruit/py-pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
