travis:
  secure:
    BINSTAR_TOKEN: dxbrM4Az0DXBP2k+YidkhPqNAQKP7TZ1DdEqhUlDfCnXspFZ6RogvcL23beal0tSD0NWrnErfliVtNt2zoTmJOtOMwLiXdfj293MbY/tG8iTMiRKhVBMR1ysm1SVJcC28RqWjr0UdE9LGb9eby/Rq4PJMZ8dY5Nck82uRL+V1TGg4dqHw5mWVWPEyi/qTwLNwGMB7Xy98zMJuVIVt7KtjaNout5yS04CR/3Pw8dBV5Tk6u1Ggz/QrKOb7V35sHaNW/Baw49M22kiM/hoz7nTp1PewJWD85a5Ldbq5JnJmFrfrfCTBN18XscYvdDpSaF5QyFv0SA82Zrm6cSSYuj8eu7shcsZ7MttXytzSCoHFi7WHSuAuT8rZA/H1zvfGpzsrhKl296aU8ZLfpwCbZyBnhdUDh+6h7iGWPM7rBUzFEv3ZUwARr742rHtLvYlEWp+IbxwpBpnsGTFN0aGbtUIGUm0F7fD7C1jg9CEQGZtWlP1ZZMUjFsjfODCgmMdHQdZg2VsUbl8j7XHvtK4I1+WCu6d1NUHS/Om6ePDFfcFaRlDNcdujMEwcYR/UjId35zBOlsJmldhzilhxH/kOsvDEHg2wJ90SPXkp1Rhj/r0aXv9EEenOo2GGS8l+jyK8EliYUb2pxZU/bt16h0NOWfqD334fm5flId3xZn2fnd6IzY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
